### ISSUE TITLE
Test/acceptance environement

### ISSUE THREAD

**Issue by DajelGit** [SelSovID/svelte-app#13]
As a developer I want to test changes to my code so that I can verify that they do what I expect them to.
As a client I want to test changes to the product before they are pushed to production so that I can provide feedback to the team about what I like and don't like.

Setup CI/CD for a test and acceptance environment that runs on a server

**Comment by mees-** [comment]
Done!

**Comment by mees-** [comment]
@jcvanmulligen @MKroezen Jullie kunnen nu wanneer je wil de app bekijken op https://ssi.s.mees.io
